[package]
name = "gc-generic-std"
version = "0.1.0"
authors = ["host"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-std = "0.1.0"
